services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual
    build: .
    container_name: imersao_devops_api
    # Comando para executar a aplicação com reload para desenvolvimento
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      # Mapeia o diretório atual para /app no contêiner para refletir as mudanças no código
      - .:/app
    ports:
      # Mapeia a porta 8000 do host para a porta 8000 do contêiner
      - "8000:8000"
    